// Package docgen generates reference documentation from SAGE's own source.
//
// It exists because hand-maintained reference docs rot. A config key, a
// Prometheus metric, or an admin route is added in Go, and the markdown
// describing it is updated separately or — far more often — not at all. The
// repository has already been through this: an ARCHITECTURE.md stats table
// drifted several thousand lines away from the truth while looking perfectly
// authoritative.
//
// So the rule this package enforces is: anything countable is generated,
// and only reasoning is written by hand. The generators read the source of
// truth (the config structs, the metrics registry, the router's mux) and emit
// markdown. Golden tests in this package compare the generated output against
// the committed files under docs/, so adding a config key without documenting
// it fails CI rather than shipping a doc that quietly lies.
//
// Regenerate with `make docs`. Nothing here is imported by the gateway binary.
package docgen

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// generatedNotice heads every generated file so nobody edits the output and
// wonders why their change vanished on the next `make docs`.
const generatedNotice = "<!-- Code generated by internal/docgen. DO NOT EDIT. Run `make docs`. -->"

// structDoc is one parsed struct: its own doc comment plus its fields in
// declaration order.
type structDoc struct {
	name   string
	doc    string
	fields []fieldDoc
}

// fieldDoc is one struct field carrying a yaml tag.
type fieldDoc struct {
	yamlKey  string
	goName   string
	typeExpr ast.Expr
	doc      string
}

// pkgDoc is one parsed package: its struct declarations, plus the named
// non-struct types those structs refer to.
//
// The named types are carried because a field's Go type name is not what an
// operator writes. config.FeatureFlags is `map[string]bool` in YAML, and
// rendering it as "FeatureFlags" would document a name that appears nowhere in
// a config file.
type pkgDoc struct {
	structs map[string]*structDoc
	named   map[string]ast.Expr
}

// parseStructs reads every non-test .go file in dir and returns the type
// declarations found.
//
// It parses rather than reflects on purpose: doc comments are the most useful
// half of the output and they do not survive into the type system, so
// reflection could produce a list of keys but never an explanation of one.
func parseStructs(dir string) (*pkgDoc, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", dir, err)
	}

	fset := token.NewFileSet()
	out := &pkgDoc{structs: map[string]*structDoc{}, named: map[string]ast.Expr{}}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", name, err)
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					// Not a struct to recurse into, but still needed so
					// typeName can render the underlying map or slice.
					out.named[ts.Name.Name] = ts.Type
					continue
				}
				// A single-spec GenDecl carries the doc comment on the
				// GenDecl, not on the TypeSpec.
				doc := ts.Doc.Text()
				if doc == "" {
					doc = gen.Doc.Text()
				}
				out.structs[ts.Name.Name] = &structDoc{
					name:   ts.Name.Name,
					doc:    strings.TrimSpace(doc),
					fields: collectFields(st),
				}
			}
		}
	}
	return out, nil
}

// collectFields extracts the yaml-tagged fields of a struct in declaration
// order. Fields tagged `yaml:"-"` or untagged are skipped: they are not
// configuration, so they do not belong in a configuration reference.
func collectFields(st *ast.StructType) []fieldDoc {
	var out []fieldDoc
	for _, f := range st.Fields.List {
		if f.Tag == nil || len(f.Names) == 0 {
			continue
		}
		key := yamlKey(f.Tag.Value)
		if key == "" || key == "-" {
			continue
		}
		doc := f.Doc.Text()
		if doc == "" {
			doc = f.Comment.Text()
		}
		out = append(out, fieldDoc{
			yamlKey:  key,
			goName:   f.Names[0].Name,
			typeExpr: f.Type,
			doc:      strings.TrimSpace(doc),
		})
	}
	return out
}

// yamlKey pulls the name out of a struct tag literal, e.g. `yaml:"port"`.
func yamlKey(tag string) string {
	tag = strings.Trim(tag, "`")
	idx := strings.Index(tag, `yaml:"`)
	if idx < 0 {
		return ""
	}
	rest := tag[idx+len(`yaml:"`):]
	end := strings.Index(rest, `"`)
	if end < 0 {
		return ""
	}
	// Strip yaml options such as ",omitempty".
	name, _, _ := strings.Cut(rest[:end], ",")
	return name
}

// typeName renders a type expression the way a config author would recognise
// it, not the way Go spells it — a time.Duration is a duration string in YAML,
// and saying "time.Duration" invites someone to write a number of nanoseconds.
func (p *pkgDoc) typeName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		if under, ok := p.named[t.Name]; ok {
			return p.typeName(under)
		}
		return goTypeToYAML(t.Name)
	case *ast.SelectorExpr:
		if pkg, ok := t.X.(*ast.Ident); ok {
			return goTypeToYAML(pkg.Name + "." + t.Sel.Name)
		}
		return t.Sel.Name
	case *ast.ArrayType:
		return "list of " + p.typeName(t.Elt)
	case *ast.MapType:
		return fmt.Sprintf("map of %s → %s", p.typeName(t.Key), p.typeName(t.Value))
	case *ast.StarExpr:
		return p.typeName(t.X)
	default:
		return "object"
	}
}

// goTypeToYAML maps Go type names onto what an operator actually writes.
func goTypeToYAML(name string) string {
	switch name {
	case "time.Duration":
		return "duration"
	case "int", "int64", "uint64":
		return "integer"
	case "float64", "float32":
		return "number"
	case "bool":
		return "boolean"
	case "string":
		return "string"
	default:
		return name
	}
}

// isStructRef reports whether a field's type resolves to another struct in the
// same parsed set, and returns it — so the walker knows to recurse rather than
// treat the field as a leaf.
func (p *pkgDoc) isStructRef(e ast.Expr) (*structDoc, bool) {
	switch t := e.(type) {
	case *ast.Ident:
		s, ok := p.structs[t.Name]
		return s, ok
	case *ast.ArrayType:
		return p.isStructRef(t.Elt)
	case *ast.MapType:
		return p.isStructRef(t.Value)
	case *ast.StarExpr:
		return p.isStructRef(t.X)
	}
	return nil, false
}

// pathSuffix marks how a nested block repeats, so a reader can tell a single
// nested object from a list of them without reading the Go source.
func pathSuffix(e ast.Expr) string {
	switch e.(type) {
	case *ast.ArrayType:
		return "[]"
	case *ast.MapType:
		return ".<name>"
	}
	return ""
}

// joinPath builds a dotted YAML path, tolerating the empty root.
func joinPath(parent, key string) string {
	if parent == "" {
		return key
	}
	return parent + "." + key
}

// mdEscape makes a doc comment safe to place inside a markdown table cell:
// newlines become spaces and pipes are escaped, since a table row cannot span
// lines.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	fields := strings.Fields(s)
	return strings.Join(fields, " ")
}
